config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/facebook/callback', to: 'sessions#create'
  root to: "sessions#index"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users, only: [:new, :create, :show] do
    resources :achievements, only: [:index, :show, :new]
  end
  resources :achievements, only: [ :create, :edit, :update, :destroy]
  resources :goals, only: [:new, :create]
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :goal
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  validates :value, format: { with: /[0-9]/, message: " must be a number"}
  scope :completed, -> { where(completed: true)} # make sure to use this to sort by completed
  scope :in_progress, -> { where(completed: false)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :achievements
  has_many :users, through: :achievements
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :achievements
  has_many :goals, through: :achievements
  has_secure_password

  def achievement_score
    score = 0
    self.achievements.each do |achievement|
      if achievement.completed
        score += achievement.value
      end
    end
    score
  end

  def unique_goals
    self.goals.pluck(:category).uniq
  end

  def self.find_or_create_facebook_account(params)
    user = User.find_by(uid: params["uid"])
    if !user
      user = User.new
      user.uid = params["uid"]
      user.facebook_name = params['info']["name"]
      user.password = "fake"
      user.save
    end
    user
  end

  def facebook_account?
    if self.uid.nil?
      false
    else
      true
    end
  end
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :current_user
  before_action :current_achievement, only: [:show, :edit, :update]
  
  def index
    achievements = @user.achievements
    @finished_achievements = achievements.completed
    @in_progress_achievements = achievements.in_progress
  end

  def new
    redirect_if_not_logged_in
    @achievement = Achievement.new
    @achievement.user_id = @user.id
  end

  def create
    @achievement = Achievement.new(achievement_params)
    if @achievement.save
      redirect_to user_achievement_path(@user, @achievement)
    else
      render :new
    end
  end

  def show
    redirect_if_not_belonging_to_current_user(@achievement)
  end

  def edit
    redirect_if_not_belonging_to_current_user(@achievement)
  end

  def  update
    if @achievement.update(achievement_params)
      redirect_to user_achievement_path(@user, @achievement)
    else
      render :edit
    end
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :value, :completed, :user_id, :goal_id)
  end

  def current_achievement
    @achievement = Achievement.find_by(id: params[:id])
  end

  def redirect_if_not_belonging_to_current_user(achievement)
    if !achievement || current_user.id != achievement.user_id
      flash.alert = "You can't edit an achievement that isn't yours, so we'll take you to your list of achievements."
      redirect_to user_achievements_path(current_user) # We want to redirect users to their achievements index page once it's in the code.
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :redirect_if_not_logged_in

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def redirect_if_not_logged_in
    if !current_user
      redirect_to '/login'
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    # list them all for a specific user
  end

  def new
    redirect_if_not_logged_in
    @goal = Goal.new
    @user = current_user
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.valid?
      # binding.pry
      @goal.save
      redirect_to user_path(current_user)
    else
      @user = current_user
      render :new
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:category)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index # home page
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def new
    if current_user
      redirect_to user_path(current_user)
    end
    # we let rails implicitly render our view for logging in
  end

  def create
    if facebook_login?(auth_params)
      user = User.find_or_create_facebook_account(auth_params)
      authenticated = true
    else
      user = User.find_by(username: params[:username])
      authenticated = user.try(:authenticate, params[:password])
    end
    if authenticated
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.alert = "Wrong username/password combination, make sure not to leave either field blank."
      redirect_to "/login"
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end

  private

  def facebook_login?(params)
    if params
      true
    else
      false
    end
  end

  def auth_params
    request.env['omniauth.auth'] ||= nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    if !current_user
      @user = User.new
    else
      flash.alert = "You are already logged in."
      redirect_to user_path(current_user)
    end
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else 
      flash.alert = "Must provide a Username when creating an account"
      redirect_to new_user_path
    end
  end

  def show
    if current_user && current_user.id == session[:user_id]
      @user = current_user
    else
      flash.alert = "The page you tried to go to wasn't yours, so you were redirected."
      redirect_to '/'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_name(user)
    if !!user.uid
      user.facebook_name
    else
      user.username
    end
  end

  def achievement_status(achievement)
    if achievement.completed
      "Completed - "
    else
      "In Progress - "
    end
  end
end

app/views/achievements/edit.html.erb
<h1>Editing the "<%= @achievement.title%>" Achievement</h1>
<%= render 'shared/form_errors', object: @achievement %>
<%= form_for @achievement do |f| %>
  <%= f.label :title, "What is the title for this achievement?" %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :description, "What must you do to complete this achievement?" %>
  <br>
  <%= f.text_area :description %>
  <br>
  <br>
  <%= f.label :value, "How many points is this achievement worth?" %>
  <%= f.number_field :value %>
  <br>
  <br>
  <%= f.label :completed, "Is this completed?" %>
  <%= f.check_box :completed %>
  <br>
  <br>
  <%= f.label :goal_id, "What goal does this work towards?" %>
  <%= f.collection_select  :goal_id, Goal.all, :id, :category %>
  <br>
  <br>
  <%= f.submit "Update Achievement" %>
<% end %>
<br>
<p><%= link_to "Back to Achievements", user_achievements_path(@user) %> - <%= link_to "Back to Home Page", user_path(@user) %></p>

app/views/achievements/index.html.erb
<h1><%= user_name(@user) %>'s achievements</h1>
<% flash.each do |type, msg| %>
<div>
  <%= msg %>
</div>
<% end %>
<h3>Completed Achievements</h3>
<ul>
  <% @finished_achievements.each do |achievement| %>
    <li><%= achievement_status(achievement) %>(<%= achievement.value %>) <%= achievement.title %> - <%= achievement.description %> <%= link_to "Edit this achievement", edit_achievement_path(achievement) %></li>
  <% end %>
</ul>
<h3>Achievements In-Progress</h3>
<ul>
  <% @in_progress_achievements.each do |achievement| %>
    <li><%= achievement_status(achievement) %>(<%= achievement.value %>) <%= achievement.title %> - <%= achievement.description %> <%= link_to "Edit this achievement", edit_achievement_path(achievement) %></li>
  <% end %>
</ul>
<p><%= link_to "Back to Home Page", user_path(@user) %></p>

app/views/achievements/new.html.erb
<h1>Create an Achievement</h1>
<%= render 'shared/form_errors', object: @achievement %>
<%= form_for @achievement do |f| %>
  <%= f.label :title, "What is the title for this achievement?" %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :description, "What must you do to complete this achievement?" %>
  <br>
  <%= f.text_area :description %>
  <br>
  <br>
  <%= f.label :value, "How many points is this achievement worth?" %>
  <%= f.number_field :value %>
  <br>
  <br>
  <%= f.label :goal_id, "What goal does this work towards?" %>
  <%= f.collection_select  :goal_id, Goal.all, :id, :category %>
  <%= f.hidden_field :user_id, value: @achievement.user_id %>
  <br>
  <%= f.submit "Create Achievement" %>
<% end %>
<br>
<p><%= link_to "Back to Achievements", user_achievements_path(@user) %> - <%= link_to "Back to Home Page", user_path(@user) %></p>

app/views/achievements/show.html.erb
<h1><%= @achievement.title %> - <%= @achievement.value %></h1>
<h3><%= @achievement.description %></h3>

<% if @user %>
  <%= link_to "Edit this achievement", edit_achievement_path(@achievement) %>
<% end %>
<br>
<p><%= link_to "Back to Achievements", user_achievements_path(@user) %> - <%= link_to "Back to Home Page", user_path(@user) %></p>

app/views/goals/edit.html.erb
<h1>The current goal is : <%= @goal.category %></h1>
<%= form_for @goal do |f| %>
  <%= f.label :category, "What should the goal be for instead?" %>
  <br>
  <%= f.text_field :category %>
  <br>
  <br>
  <%= f.submit "Update Goal" %>
<% end %>
<br>
<p><%= link_to "Back to Home Page", user_path(@user) %></p>

app/views/goals/new.html.erb
<h1>Create a Goal!</h1>
<p>Your goal will act like the category for achievements to fall under.</p>
<%= render "shared/form_errors", object: @goal%>
<%= form_for @goal do |f| %>
  <%= f.label :category, "What is the goal you want to accomplish?" %>
  <br>
  <%= f.text_field :category %>
  <br>
  <br>
  <%= f.submit "Create Goal" %>
<% end %>
<br>
<p><%= link_to "Back to Home Page", user_path(@user) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AchievementTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if current_user %>
      <%= link_to "Logout", { controller: "sessions", action: "destroy"}, method: :delete %>
    <% end %>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="form_errors">
      <h3>Looks like there were some errors creating your <%= object.class %>.</h3>
      <ul>
          <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Welcome to Achievement Tracker, please sign up below :)</h1>
<% flash.each do |type, msg| %>
<div>
  <%= msg %>
</div>
<% end %>
<%= form_for @user do |f| %>
  <%= f.label :username, "Create your Username: " %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :password, "Create your password: " %>
  <%= f.password_field :password %>
  <br>
  <br>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome back <%= user_name(@user) %>!</h1>
<% flash.each do |type, msg| %>
<div>
  <%= msg %>
</div>
<% end %>
<h3>Right now you have an achievement score of <%= @user.achievement_score %></h3>
<p>Your current goals are :</p>
<ul>
  <% @user.unique_goals.each do |goal| %>
    <li><%= goal %></li>
  <% end %>
</ul>
<br>
<p>Below are some links to do the following:</p>
<ul>
  <li><%= link_to "create a goal", new_goal_path %></li>
  <li><%= link_to "create a new achievement", new_user_achievement_path(@user) %></li>
  <li><%= link_to "view your achievements", user_achievements_path(@user) %></li>
</ul>